### ISSUE TITLE
Task copying bower packages to `lib` even if `copy` is set to false

### ISSUE THREAD

**Issue by joshuacc** [yatskevich/grunt-bower-task#65]
Running `grunt bower` creates a `lib` directory even if I set `copy` to false. My setup is below:

``` coffeescript
bower:
  install:
    copy: false
```

Is there some other setting I need to use?

**Comment by fantactuka** [comment]
You missed `options` block which is require by grunt to pass the properly

```
bower:
  install:
    options:
      copy: false
```
